Feature
MILINDI7/Hello_world pull request #1
Opened 2022-08-18 16:58 UTC by MILINDI7

2022-08-18 17:30 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @MILINDI7, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - Professional README file. ✔️
 - Correct use of GitHub flow. ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] You should add a title and a description of the changes you make to the project in your Pull Request so the person that will review your code will understand and have an idea of what this PR is about and what files to analyze. Kindly add a title and a description to this PR.
- [ ] You used the correct GitHub flow but you should name your branches in a more descriptive way. Take a look at [this](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) article and [this](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) for renaming a branch.
- [ ] You forgot to add the `test.md` file to your project. Kindly add this file and don't forget to add it to the `.gitignore`.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 17:30 UTC, leonardodiasb commented on README.md
> +- to run this web you should have a webbrowser like chrome, safari, firefox...
- [ ] For headings in markdown files it is required to use a space after the `#` symbols. Try using a space and take a look at the style of your heading after that.

2022-08-18 17:30 UTC, leonardodiasb commented on .gitignore
> +
- [ ] As the project required, you should add the `node_modules` and the `test.md` file to your `.gitignore` file. Kindly add those files to it.

2022-08-18 18:16 UTC, MILINDI7 commented
Add the test.md

2022-08-18 18:30 UTC, mukhammadrizooff requested changes
Hi @MILINDI7, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors ✔️ 
- Descriptive commit history ✔️ 

 ## Required Changes ♻️
- [ ] [REQUIRED] Please delete `test.md` file and recreate it because your `.gitignore` file is not working!

![image](https://user-images.githubusercontent.com/63915024/185467071-46b10014-27c4-465e-bb4b-5943819eecbf.png)

- [ ] [REQUIRED] Pull Request should have a summary describing introduced changes in more detail.

![image](https://user-images.githubusercontent.com/63915024/185467568-0b43b61f-016d-4890-816a-97baf066d3be.png)

- [ ] [REQUIRED] Pull Request should have a descriptive title telling you what changes are inside.

![image](https://user-images.githubusercontent.com/63915024/185467745-73fe5582-89ca-4e33-a603-23486e9c517f.png)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 18:30 UTC, mukhammadrizooff commented on README.md
> +
- [ ] [REQUIRED] Please give name to `line 3` and give also descriptive description about your project to `line 5 to 7` name and description should be descriptive.

2022-08-19 05:13 UTC, Ismailco requested changes
### Hi @MILINDI7, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 05:13 UTC, Ismailco commented on .gitignore
> +./test.md
- [ ] [OPTIONAL] Kindly add the `node_modules` folder to your `.gitignore` so it will not be submitted by accident to your remote/Github repository

2022-08-19 05:13 UTC, Ismailco commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] As the previous reviewer suggested kindly change the name of the PR to an action e.g `Setup the repository` so it reflects the changes inside the PR

2022-08-19 05:13 UTC, Ismailco commented on README.md
> +the heading color is blue
- [ ] As the previous reviewer suggested kindly change the name of the project e.g `Hello Microverse` and add a descriptive description in your README

2022-08-19 05:46 UTC, topeogunleye approved these changes
### Hi @MILINDI7, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 05:52 UTC, merged